os:
  - linux
  # - windows

language: python
install:
  - pip install -r requirements.txt
  - pip install -U platformio
  - pip install pyinstaller

script:
  - ./buildFirmware.sh
  - pyinstaller main-onedir.spec
